# Generated by Django 4.2.8 on 2026-06-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hosting_ended_at_alter_hosting_people_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hosting',
            new_name='Session',
        ),
        migrations.RenameModel(
            old_name='Reimbursement',
            new_name='TabAdjustment',
        ),
    ]
