# Generated by Django 4.2.8 on 2026-06-02 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_hosting_to_session_reimbursement_to_tabadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabadjustment',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tab_adjustments', to='api.tab'),
        ),
    ]
