# Generated by Django 4.2.8 on 2026-06-02 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tabadjustment_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'PIN must be exactly 6 digits')]),
        ),
        migrations.AddField(
            model_name='tab',
            name='pin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tab',
            name='pin_required',
            field=models.BooleanField(default=False),
        ),
    ]
