# Generated by Django 4.2.8 on 2026-06-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_convert_large_purchases_to_tab_adjustments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
