# Generated by Django 4.2.30 on 2026-06-21 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_purchase_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
