# Generated by Django 4.2.30 on 2026-06-21 10:20

from django.db import migrations


def backfill(apps, schema_editor):
    from django.db.models import F
    Purchase = apps.get_model('api', 'Purchase')
    Purchase.objects.update(occurred_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_client_uuid_and_occurred_at'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
