# Generated by Django 4.2.30 on 2026-06-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_inventory_and_cash_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_type',
            field=models.CharField(blank=True, choices=[('in', 'Sisään'), ('out', 'Ulos'), ('cash', 'Käteinen')], max_length=4, null=True),
        ),
    ]
