# Generated by Django 4.2.30 on 2026-06-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_purchase_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='ignore_balance_limit',
            field=models.BooleanField(default=False),
        ),
    ]
