# Generated by Django 4.2.30 on 2026-06-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_tab_ignore_balance_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='last_purchase_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
