# Generated by Django 4.2.30 on 2026-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_tab_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('host_only', 'Host only, no purchases'), ('enabled', 'Enabled'), ('archived', 'Archived')], default='enabled', max_length=10),
        ),
    ]
